### ISSUE TITLE
Möglicher inhaltlicher Fehler

### ISSUE THREAD

**Issue by ArvedF** [f-grubm/ana2-skript#19]
Satz 1.2. Beweis: müsste es nicht so sein:
"ln x Ungleichung (ii). (ii) geht in (i) über"
Also (ii) und (i) gerade vertauschen?

**Comment by f-grubm** [comment]
Habe das jetzt mal geändert. Die neue Richtung ist für mich logischer. Ich hab mir nur die andere Richtung aufgeschrieben. Werde mir das aber nochmal genauer ansehen

**Comment by f-grubm** [comment]
Ja, okay, es stimmt jetzt so!
