### ISSUE TITLE
Landau Symbol

### ISSUE THREAD

**Issue by ArvedF** [f-grubm/ana2-skript#30]
Landau Symbol in Contributing-Info einfügen und in der Präambel so konfigurieren, dass danach nicht alles kleiner ist

**Comment by ArvedF** [comment]
Gradient auch, Befehl definiert als \grad

**Comment by f-grubm** [comment]
\landau und \grad sind definiert, beide sind auch schon in CONTRIBUTING.md (auch Nabla)
