### ISSUE TITLE
Warum so viel kursiv?

### ISSUE THREAD

**Issue by f-grubm** [f-grubm/ana2-skript#33]
S. 61, Vorlesung: 04.06.2019, nach Def. 2.1: möglicherweise nicht die gesamte Phrase "bis zur ersten Ordnung affin-linear approximiert" hervorheben.

**Comment by ArvedF** [comment]
So war es an der Tafel unterstrichen... die ersten beiden Wörter könnte man vielleicht ausnehmen

**Comment by f-grubm** [comment]
Passt,lassen wir‘s
