### ISSUE TITLE
Klammern vergessen

### ISSUE THREAD

**Issue by f-grubm** [f-grubm/ana2-skript#42]
Vorlesung 13.06.2019, S. 73, Beweis Satz 2.1: in der ersten Zeile der ersten multline*-Umgebung sollte sich das 1/h_j auf beide folgenden Terme (also bis zum Gleichheitszeichen) beziehen; es gehört also alles nach dem 1/h_j eingeklammert…

**Comment by ArvedF** [comment]
erledigt
